apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aq4xhuql2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aq4xhuql2-go 
  name: aq4xhuql2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aq4xhuql2-go 
